
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = "COMMA CONDITION ELSE IF STRINGexpression : IF CONDITION COMMA expression COMMA expression ')' expression : ELSE expression expression : CONDITION "
    
_lr_action_items = {'IF':([0,4,7,9,],[2,2,2,2,]),'ELSE':([0,4,7,9,],[4,4,4,4,]),'CONDITION':([0,2,4,7,9,],[3,5,3,3,3,]),'$end':([1,3,6,11,],[0,-3,-2,-1,]),'COMMA':([3,5,6,8,11,],[-3,7,-2,9,-1,]),')':([3,6,10,11,],[-3,-2,11,-1,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,4,7,9,],[1,6,8,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> IF CONDITION COMMA expression COMMA expression )','expression',7,'p_expression_if','pyparser_3.py',27),
  ('expression -> ELSE expression','expression',2,'p_expression_else_if','pyparser_3.py',31),
  ('expression -> CONDITION','expression',1,'p_expression_condition','pyparser_3.py',35),
]
